[versions]
agp = "8.13.0"
cameraCamera2 = "1.2.3"
cameraView = "1.5.1"
cameraViewVersion = "1.3.2"
faceDetection = "16.1.7"
faceDetectionVersion = "16.1.5"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.11.0"
constraintlayout = "2.1.4"
okhttp = "5.3.0"
zxingAndroidEmbedded = "4.3.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraView" }
androidx-camera-camera2-v123 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraViewVersion" }
androidx-camera-view-v132 = { module = "androidx.camera:camera-view", version.ref = "cameraViewVersion" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraView" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
face-detection-v1615 = { module = "com.google.mlkit:face-detection", version.ref = "faceDetectionVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

